[package]
name = "enclave_kmstool"
version = "0.1.0"
authors = ["mike"]
edition = "2018"

[dependencies]
libc = "0.2.170"
anyhow = { version = "1.0" }
log = "0.4.25"
byteorder = "1.3"
thiserror = "2.0.11"
typed-builder = "0.20.0"

[build-dependencies]
bindgen = "0.71.1"
