[package]
name = "enclave_agent"
version = "0.1.0"
authors = ["mike"]
edition = "2018"

[dependencies]
anyhow = { version = "1.0" }
typed-builder = { version = "0.20.0" }
log = "0.4"
env_logger = { version = "0.11.6" }
byteorder = "1.3"
vsock = "0.5.1"
thiserror = "2.0.11"