[package]
name = "enclave_agent"
version = "0.1.0"
authors = ["mikerfrr"]
edition = "2018"

[dependencies]
anyhow = {version = "1.0"}
typed-builder = {version = "0.20.0"}
log = {version = "0.4"}
env_logger = {version = "0.11.6"}
vsock = {version = "0.5.1"}
thiserror = {version = "2.0.11"}