[package]
name = "vaultron_enclave"
version = "0.1.0"
authors = ["mikerfrr"]
edition = "2018"

[features]
default = []
# Mock KMS functionality for CI/CD workflows and testing
workflow_build_feature = []

[dependencies]
anyhow = {version = "1.0"}
log = {version = "0.4.25"}
env_logger = {version = "0.11.6"}
vsock = {version = "0.5.1"}
thiserror = {version = "2.0.11"}
serde_json = {version = "1.0.139"}
typed-builder = {version = "0.20.0"}

enclave_kmstool = { path = "../enclave_kmstool" }