[package]
name = "enclave_protos_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = {version = "1.0.79"}
quote = {version = "1.0.35"}
syn = {version = "2.0.52", features = ["full", "extra-traits"]}
