name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: amazonlinux:2023
    steps:
      - name: Install required tools
        run: |
          dnf update -y
          dnf install -y tar make

      - name: Checkout
        uses: actions/checkout@v3

      - name: Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.86.0

      - name: Install required tools
        run: make build-elf-install

      - name: Build binaries
        run: make build

      - name: make docker image
        run: make img

      - name: Build EIF
        run: make eif

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/vaultron/vaultron-enclave
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Docker Push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          load: true

      - name: Create Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: |
            target/elf/vaultron_enclave.eif
            target/release/vaultron_enclave
            target/release/vaultron_enclave_agent
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
