name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    container:
      image: amazonlinux:2023
    steps:
      - name: Install required tools
        run: |
          dnf update -y
          dnf install -y tar make

      - name: Checkout
        uses: actions/checkout@v3

      - name: Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.86.0

      - name: Install required tools
        run: make build-elf-install

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/fairxfun/vaultron-enclave
          tags: |
            type=semver,pattern={{version}}
            type=sha

      - name: Build binaries
        run: make build

      - name: Build EIF
        id: build_eif
        run: |
          make eif | tee eif_output.txt
          echo "EIF_MEASUREMENTS=$(jq -Rsa . eif_output.txt)" >> $GITHUB_ENV

      - name: Build checksums
        run: make checksums

      - name: Docker Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./container/enclave/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: |
            target/x86_64-unknown-linux-gnu/elf/vaultron_enclave.eif
            target/x86_64-unknown-linux-gnu/elf/vaultron_enclave.eif.sha256
            target/x86_64-unknown-linux-gnu/release/vaultron_enclave
            target/x86_64-unknown-linux-gnu/release/vaultron_enclave.sha256
            target/x86_64-unknown-linux-gnu/release/vaultron_enclave_agent
            target/x86_64-unknown-linux-gnu/release/vaultron_enclave_agent.sha256
          body: |
            EIF Measurements:
            ```json
            ${{ fromJSON(env.EIF_MEASUREMENTS) }}
            ```
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
